export enum ServerProtocol {
    HEARTBEAT,
    LISTEN_DATASOURCE_OK,
    LISTEN_DATASOURCE_ERR,
    LISTEN_ARRAY_DATASOURCE_OK,
    LISTEN_ARRAY_DATASOURCE_ERR,
    UPDATE_DATASOURCE,
    UPDATE_ARRAY_DATASOURCE,
}
